sass:
  sass_dir: _sass

url: "alohabowlsandtea.github.io"
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false
